language: php
dist: trusty
php:
  - '5.4'
  - '5.5'
  - '7.3'
  - '7.4'
  - nightly
matrix:
  allow_failures:
  - php: nightly
cache:
  directories:
    - $HOME/.composer/cache/files
install:  composer install
script:   vendor/bin/phpunit --bootstrap vendor/autoload.php tests
