language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm
  - nightly
cache:
  directories:
    - $HOME/.composer/cache/files
install:  composer install
script:   vendor/bin/phpunit --bootstrap vendor/autoload.php tests
